version: '3'

services:
  domserver:
    container_name: domserver
    image: domjudge/domserver:8.2.1
    ports:
      - "443:80"
    volumes:
      - ./ui/public:/opt/domjudge/domserver/webapp/public
      - ./ui/templates:/opt/domjudge/domserver/webapp/templates
      - ./nginx:/etc/nginx/conf.d
      - ./php/php.ini:/etc/php/7.3/cli/php.ini
    env_file:
      - domserver.env
