version: '3'

services:
  judgehost:
    image: domjudge/judgehost:8.1.0
    container_name: judgehost-0
    hostname: judgehost
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    env_file:
      - judgehost.env
